# Generated by Django 4.2.10 on 2026-01-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0002_remove_comunicacionescircular_activa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioshorario',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
