# Generated by Django 4.2.10 on 2026-01-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0003_remove_horarioshorario_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosdetalle',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='fecha_vigencia_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='tipo_horario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
