# Generated by Django 4.2.10 on 2026-01-30 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0004_alter_horariosdetalle_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioshorario',
            name='horario_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucesores', to='databaseModels.horarioshorario'),
        ),
    ]
