# Generated by Django 4.2.10 on 2026-02-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0005_alter_horarioshorario_horario_anterior'),
        ('databaseModels', '0006_insert_roles'),
    ]

    operations = [
    ]
