# Generated by Django 4.2.10 on 2026-02-05 02:55

import apps.databaseModels.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0007_merge_20260203_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='comunicaciones/materiales/', validators=[apps.databaseModels.validators.validar_extension_archivo])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material de Comunicación',
                'db_table': 'comunicaciones_material',
            },
        ),
    ]
