# Generated by Django 4.2.10 on 2026-02-05 04:58

import apps.databaseModels.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0008_comunicacionmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacionescircular',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='circulares/', validators=[apps.databaseModels.validators.validar_extension_archivo]),
        ),
    ]
