# Generated by Django 4.2.10 on 2026-02-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0007_merge_20260201_0626'),
        ('databaseModels', '0009_alter_comunicacionescircular_archivo_adjunto'),
    ]

    operations = [
    ]
