# Generated by Django 4.2.10 on 2026-02-12 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0010_merge_20260205_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosdetalle',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_horario_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabeceras_horario_docentec', to=settings.AUTH_USER_MODEL),
        ),
    ]
