# Generated by Django 4.2.10 on 2026-02-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0011_alter_horariosdetalle_docente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosrepositorio',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='documentosrepositorio',
            name='es_publico',
        ),
        migrations.RemoveField(
            model_name='documentosrepositorio',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='documentosrepositorio',
            name='permisos_escritura',
        ),
        migrations.RemoveField(
            model_name='documentosrepositorio',
            name='permisos_lectura',
        ),
        migrations.RemoveField(
            model_name='documentosrepositorio',
            name='tipo_contenido',
        ),
        migrations.AddField(
            model_name='documentosrepositorio',
            name='cloudinary_path',
            field=models.CharField(default=0, max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentosrepositorio',
            name='puede_escribir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentosrepositorio',
            name='rol_acceso',
            field=models.CharField(default='Administrador', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentosrepositorio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
