# Generated by Django 4.2.10 on 2026-02-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('databaseModels', '0012_remove_documentosrepositorio_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosdocumento',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='documentosdocumento',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='documentosdocumento',
            index=models.Index(fields=['content_type', 'object_id'], name='documentos__content_fe825b_idx'),
        ),
    ]
