# Generated by Django 4.2.10 on 2026-02-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0014_hu19_comunicados'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comitesreunion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comitesreunion',
            name='fecha_convocatoria',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='comitesreunion',
            name='comite',
        ),
        migrations.RemoveField(
            model_name='comitesreunion',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='comitesreunion',
            name='numero_reunion',
        ),
    ]
