# Generated by Django 4.2.10 on 2026-03-12 17:54

from django.db import migrations

def create_patronato_repository(apps, schema_editor):
    DocumentosRepositorio = apps.get_model('databaseModels', 'DocumentosRepositorio')

    DocumentosRepositorio.objects.get_or_create(
        nombre="Informes Patronato",
        defaults={
            'descripcion': 'Repositorio central para informes económicos del Patronato',
            'cloudinary_path': 'patronato/informes',
            'rol_acceso': 'Administrador',
            'puede_escribir': True
        }
    )
    
class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0015_alter_comitesreunion_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(create_patronato_repository),
    ]
