# Generated by Django 4.2.10 on 2026-04-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0016_setup_patronato_repo'),
        ('databaseModels', '0017_circulares_upload_path_home_circular'),
    ]

    operations = [
    ]
