# Generated by Django 5.1.6 on 2026-04-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0016_setup_patronato_repo'),
        ('databaseModels', '0017_circulares_upload_path_home_circular'),
    ]

    operations = [
    ]
