# Generated by Django 4.2.10 on 2026-06-16 04:29

import apps.databaseModels.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0022_comitesmiembro_unique_persona_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicacionescircular',
            options={'managed': True, 'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='comunicacionescomunicado',
            options={'managed': True, 'ordering': ['-fecha_publicacion']},
        ),
        migrations.RemoveField(
            model_name='comunicacionescircular',
            name='tipo_comunicado',
        ),
        migrations.AlterField(
            model_name='academicogrupo',
            name='estado',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='academicomatricula',
            name='estado',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='academicoperiodo',
            name='año_lectivo',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='academicoperiodo',
            name='estado',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='authauditorialog',
            name='accion',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='authauditorialog',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='authauditorialog',
            name='modulo',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='comunicacionescircular',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='circulares/', validators=[apps.databaseModels.validators.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='comunicacionescircular',
            name='categoria',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comunicacionescircular',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulares_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicacionescircular',
            name='destinatarios',
            field=models.CharField(choices=[('docentes', 'Docentes'), ('estudiantes', 'Estudiantes'), ('todos', 'Todos')], db_index=True, default='todos', max_length=20),
        ),
        migrations.AlterField(
            model_name='comunicacionescircular',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('archivada', 'Archivada')], db_index=True, default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='comunicacionescircular',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comunicacionescircular',
            name='fecha_vigencia_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='comunicacionescircular',
            name='titulo',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comunicacionescomunicado',
            name='fecha_publicacion',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comunicacionescomunicado',
            name='tipo_comunicado',
            field=models.CharField(choices=[('informativo', 'Informativo'), ('urgente', 'Urgente'), ('evento', 'Evento'), ('aviso', 'Aviso'), ('felicitacion', 'Felicitación'), ('tarea', 'Tarea'), ('cambio', 'Cambio')], db_index=True, default='informativo', max_length=50),
        ),
        migrations.AlterField(
            model_name='comunicacionescomunicado',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='comunicacionesnotificacion',
            name='fecha_creacion',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='comunicacionesnotificacion',
            name='leida',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='comunicacionesnotificacion',
            name='tipo_notificacion',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluacionescalificacion',
            name='fecha_registro',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='evaluacionesevaluacion',
            name='fecha_evaluacion',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='evaluacionesevaluacion',
            name='tipo_evaluacion',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='horariosincapacidad',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='academicogrupo',
            index=models.Index(fields=['periodo', 'estado'], name='idx_grupo_periodo_estado'),
        ),
        migrations.AddIndex(
            model_name='authauditorialog',
            index=models.Index(fields=['usuario', 'fecha_hora'], name='idx_auditoria_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='authauditorialog',
            index=models.Index(fields=['modulo', 'accion'], name='idx_auditoria_modulo_accion'),
        ),
        migrations.AddIndex(
            model_name='comunicacionescircular',
            index=models.Index(fields=['estado', 'fecha_vigencia_inicio'], name='idx_circular_estado_vigencia'),
        ),
        migrations.AddIndex(
            model_name='comunicacionescircular',
            index=models.Index(fields=['destinatarios', 'estado'], name='idx_circular_dest_estado'),
        ),
        migrations.AddIndex(
            model_name='comunicacionesnotificacion',
            index=models.Index(fields=['usuario', 'leida'], name='idx_notif_usuario_leida'),
        ),
        migrations.AddIndex(
            model_name='comunicacionesnotificacion',
            index=models.Index(fields=['usuario', 'fecha_creacion'], name='idx_notif_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='evaluacionescalificacion',
            index=models.Index(fields=['estudiante', 'fecha_registro'], name='idx_calificacion_est_fecha'),
        ),
        migrations.AddIndex(
            model_name='evaluacionesevaluacion',
            index=models.Index(fields=['docente_grupo', 'fecha_evaluacion'], name='idx_eval_docgrp_fecha'),
        ),
    ]
