# Generated by Django 4.2.10 on 2026-06-16 05:05

import apps.databaseModels.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0023_indexes_and_clean_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicoasignatura',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='academicoasignatura',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicodocentegrupo',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='academicogrupo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='academicogrupo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicoperiodo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='academicoperiodo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='authauditorialog',
            name='mensaje_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authauditorialog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='authpermiso',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authrol',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authrol',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='authrolpermiso',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authsesion',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='authusuariorol',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comitesacta',
            name='fecha_elaboracion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comitesinformeorgano',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='comites/informes/', validators=[apps.databaseModels.validators.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='documentosdocumento',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentosdocumento',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documentosplantilla',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluacionesasistencia',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='asistencia/documentos/', validators=[apps.databaseModels.validators.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='evaluacionesasistencia',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluacionescalificacion',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='evaluacionesevaluacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluacionesevaluacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluacioneshistorialcalificacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='horariosdetalle',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_horario', to='databaseModels.personasdocente'),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_asignados', to='databaseModels.personasdocente'),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='horariosincapacidad',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='horarios/incapacidades/', validators=[apps.databaseModels.validators.validar_extension_archivo]),
        ),
        migrations.AlterField(
            model_name='horariosincapacidad',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='horariospermiso',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personasestudianteencargado',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personaspersona',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='PersonasPersonaRol',
        ),
    ]
