# Generated by Django 4.2.10 on 2026-06-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0024_alter_academicoasignatura_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicacionmaterial',
            options={'managed': True, 'verbose_name': 'Material de Comunicación'},
        ),
        migrations.AddField(
            model_name='documentosrepositorio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='estado',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='personaspersona',
            name='email_institucional',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='authsesion',
            index=models.Index(fields=['activa', 'fecha_expiracion'], name='idx_sesion_activa_expiracion'),
        ),
        migrations.AddIndex(
            model_name='evaluacionesasistencia',
            index=models.Index(fields=['grupo', 'fecha'], name='idx_asistencia_grupo_fecha'),
        ),
    ]
