# Generated by Django 4.2.10 on 2026-02-23 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planeamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('En revisión', 'En revisión'), ('Aprobado', 'Aprobado')], default='Borrador', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='planeamientos/')),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('comentarios', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planeamientos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
