# Generated by Django 4.2.10 on 2026-06-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeamientos', '0003_planeamiento_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeamiento',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('En revisión', 'En revisión'), ('Aprobado', 'Aprobado'), ('Archivado', 'Archivado')], default='Borrador', max_length=20),
        ),
    ]
