# Generated by Django 4.2.10 on 2026-01-22 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseModels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicacionescircular',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='comunicacionescircular',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='comunicacionescircular',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='comunicacionescircular',
            name='requiere_confirmacion',
        ),
        migrations.RemoveField(
            model_name='comunicacionescircular',
            name='roles_destinatarios',
        ),
        migrations.AddField(
            model_name='comunicacionescircular',
            name='categoria',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunicacionescircular',
            name='estado',
            field=models.CharField(default='archivado', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicoasignaturagrado',
            name='asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicoasignatura'),
        ),
        migrations.AlterField(
            model_name='academicoasignaturagrado',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicogrado'),
        ),
        migrations.AlterField(
            model_name='academicodocentegrupo',
            name='asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicoasignatura'),
        ),
        migrations.AlterField(
            model_name='academicodocentegrupo',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasdocente'),
        ),
        migrations.AlterField(
            model_name='academicodocentegrupo',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicogrupo'),
        ),
        migrations.AlterField(
            model_name='academicogrupo',
            name='docente_guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasdocente'),
        ),
        migrations.AlterField(
            model_name='academicogrupo',
            name='grado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicogrado'),
        ),
        migrations.AlterField(
            model_name='academicogrupo',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicoperiodo'),
        ),
        migrations.AlterField(
            model_name='academicogrupo',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicoseccion'),
        ),
        migrations.AlterField(
            model_name='academicomatricula',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasestudiante'),
        ),
        migrations.AlterField(
            model_name='academicomatricula',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicogrupo'),
        ),
        migrations.AlterField(
            model_name='authauditorialog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authrolpermiso',
            name='permiso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.authpermiso'),
        ),
        migrations.AlterField(
            model_name='authrolpermiso',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.authrol'),
        ),
        migrations.AlterField(
            model_name='authsesion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authusuario',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personaspersona'),
        ),
        migrations.AlterField(
            model_name='authusuariorol',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authusuariorol_asignado_por_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authusuariorol',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.authrol'),
        ),
        migrations.AlterField(
            model_name='authusuariorol',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comitesacta',
            name='aprobada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comitesacta_aprobada_por_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comitesacta',
            name='elaborada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comitesacta',
            name='reunion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.comitesreunion'),
        ),
        migrations.AlterField(
            model_name='comitescomite',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicoperiodo'),
        ),
        migrations.AlterField(
            model_name='comitesinformeorgano',
            name='elaborado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comitesinformeorgano',
            name='organo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.comitesorganoauxiliar'),
        ),
        migrations.AlterField(
            model_name='comitesinformeorgano',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicoperiodo'),
        ),
        migrations.AlterField(
            model_name='comitesmiembro',
            name='comite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.comitescomite'),
        ),
        migrations.AlterField(
            model_name='comitesmiembro',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personaspersona'),
        ),
        migrations.AlterField(
            model_name='comitesorganoauxiliar',
            name='coordinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personaspersona'),
        ),
        migrations.AlterField(
            model_name='comitesorganoauxiliar',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicoperiodo'),
        ),
        migrations.AlterField(
            model_name='comitesreunion',
            name='comite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.comitescomite'),
        ),
        migrations.AlterField(
            model_name='comitesreunion',
            name='convocada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicacionescircular',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicacionescircular',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comunicacionescomunicado',
            name='publicado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicacioneslecturacircular',
            name='circular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.comunicacionescircular'),
        ),
        migrations.AlterField(
            model_name='comunicacioneslecturacircular',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personaspersona'),
        ),
        migrations.AlterField(
            model_name='comunicacionesnotificacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentoscompartido',
            name='compartido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentoscompartido',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.documentosdocumento'),
        ),
        migrations.AlterField(
            model_name='documentosdocumento',
            name='cargado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentosdocumento',
            name='documento_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.documentosdocumento'),
        ),
        migrations.AlterField(
            model_name='documentosdocumento',
            name='repositorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.documentosrepositorio'),
        ),
        migrations.AlterField(
            model_name='documentosplantilla',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentosrepositorio',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentosrepositorio',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.documentosrepositorio'),
        ),
        migrations.AlterField(
            model_name='evaluacionesasistencia',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasestudiante'),
        ),
        migrations.AlterField(
            model_name='evaluacionesasistencia',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicogrupo'),
        ),
        migrations.AlterField(
            model_name='evaluacionesasistencia',
            name='registrada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacionescalificacion',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasestudiante'),
        ),
        migrations.AlterField(
            model_name='evaluacionescalificacion',
            name='evaluacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.evaluacionesevaluacion'),
        ),
        migrations.AlterField(
            model_name='evaluacionescalificacion',
            name='registrada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacionesevaluacion',
            name='docente_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicodocentegrupo'),
        ),
        migrations.AlterField(
            model_name='evaluacioneshistorialcalificacion',
            name='calificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.evaluacionescalificacion'),
        ),
        migrations.AlterField(
            model_name='evaluacioneshistorialcalificacion',
            name='modificada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacionespromedio',
            name='docente_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicodocentegrupo'),
        ),
        migrations.AlterField(
            model_name='evaluacionespromedio',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasestudiante'),
        ),
        migrations.AlterField(
            model_name='evaluacionespromedio',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicoperiodo'),
        ),
        migrations.AlterField(
            model_name='horariosaprobacion',
            name='aprobador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horariosaprobacion',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.horarioshorario'),
        ),
        migrations.AlterField(
            model_name='horariosdetalle',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicoasignatura'),
        ),
        migrations.AlterField(
            model_name='horariosdetalle',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasdocente'),
        ),
        migrations.AlterField(
            model_name='horariosdetalle',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.horarioshorario'),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasdocente'),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicogrupo'),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='horario_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.horarioshorario'),
        ),
        migrations.AlterField(
            model_name='horarioshorario',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.academicoperiodo'),
        ),
        migrations.AlterField(
            model_name='horariosincapacidad',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasdocente'),
        ),
        migrations.AlterField(
            model_name='horariosincapacidad',
            name='registrada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horariospermiso',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horariospermiso_aprobado_por_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horariospermiso',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasdocente'),
        ),
        migrations.AlterField(
            model_name='horariospermiso',
            name='solicitado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personasdocente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='databaseModels.personaspersona'),
        ),
        migrations.AlterField(
            model_name='personasencargado',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='databaseModels.personaspersona'),
        ),
        migrations.AlterField(
            model_name='personasestudiante',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='databaseModels.personaspersona'),
        ),
        migrations.AlterField(
            model_name='personasestudianteencargado',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasencargado'),
        ),
        migrations.AlterField(
            model_name='personasestudianteencargado',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personasestudiante'),
        ),
        migrations.AlterField(
            model_name='personaspersona',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personaspersonarol',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.personaspersona'),
        ),
        migrations.AlterField(
            model_name='personaspersonarol',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='databaseModels.authrol'),
        ),
    ]
