# Generated by Django 4.2.10 on 2026-02-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(default='General', max_length=80)),
                ('ultima_actualizacion', models.DateField(auto_now=True)),
                ('estado', models.CharField(choices=[('Publicado', 'Publicado'), ('Borrador', 'Borrador'), ('Inactivo', 'Inactivo')], default='Borrador', max_length=20)),
            ],
        ),
    ]
