# Generated by Django 4.2.10 on 2026-02-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficiosPlantillas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='plantillas/'),
        ),
    ]
