# Generated by Django 4.2.10 on 2026-02-23 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX')], default='PDF', max_length=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='exportaciones/')),
                ('actualizado', models.DateField(auto_now=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
