# Generated by Django 4.2.10 on 2026-02-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacion',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exportacion',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
