# Generated by Django 4.2.10 on 2026-03-16 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databaseModels', '0015_alter_comitesreunion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_registro', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_registro', to='databaseModels.academicogrupo')),
            ],
            options={
                'unique_together': {('grupo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tardia', 'Tardía')], default='presente', max_length=20)),
                ('justificada', models.BooleanField(default=False)),
                ('justificante', models.FileField(blank=True, null=True, upload_to='justificantes_asistencia/')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_detalle', to='databaseModels.personasestudiante')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='asistencia.asistenciaregistro')),
            ],
            options={
                'unique_together': {('registro', 'estudiante')},
            },
        ),
    ]
