# Generated by Django 4.2.10 on 2026-03-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaregistro',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
