# Generated by Django 4.2.10 on 2026-03-17 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibir_profesor_hogar', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comunicaciones_preferencia_notificacion',
                'managed': True,
            },
        ),
    ]
